from hist import Hist
from hist.axis import StrCategory, Regular, Integer, IntCategory
import hist
import numpy as np
import awkward as ak

# General Purpose
samp = StrCategory([],name="samp",label="Sample Name",growth=True)
cut = StrCategory([],name="cut",label="Cut Applied",growth=True)

# functions to make histograms
class myHisto:
    def __init__(self):
        self.histograms = {}
        self.samp = "NO_SAMPLE"
        self.cut = "NO_CUT"

        # axis compendium
        self.samp = StrCategory([],name="samp",label="Sample Name",growth=True)
        self.cut = StrCategory([],name="cut",label="Cut Applied",growth=True)
        self.ele_type = self.parse_axis(('ele_type',['L','R']))
        self.match_type = self.parse_axis(('match_type',['L','R']))
        self.match = self.parse_axis(('match',[0,1]))
        self.met = self.parse_axis(('met',100,50,300))
        self.dR = self.parse_axis(('dR',100,0,5))
        self.vxy1 = self.parse_axis(('vxy',100,0,1))
        self.vxy10 = self.parse_axis(('vxy',100,0,10))
        self.vxy100 = self.parse_axis(('vxy',100,0,100))
        self.ele_pt = self.parse_axis(("pt",50,0,50))
        self.dphi = self.parse_axis(("phi",64,-3.2,3.2))
        self.phi = self.parse_axis(("phi",64,-3.2,3.2))
        self.abs_dphi = self.parse_axis(('phi',100,0,3))
        self.eta = self.parse_axis(('eta',100,-2.5,2.5))
        self.dxy = self.parse_axis(('dxy',500,0,5))
        self.r3 = self.parse_axis(('r3',500,0,100))
        self.dxy_signif = self.parse_axis(('signif',100,0,20))
        self.trk_chi2 = self.parse_axis(('chi2',100,0,5))
        self.vtx_chi2 = self.parse_axis(('chi2',100,0,5))
        self.iso = self.parse_axis(('iso',100,0,5))
        self.sieie = self.parse_axis(('sieie',100,0,0.1))
        self.detaseed = self.parse_axis(('detaSeed',100,0,5))
        self.HoverE = self.parse_axis(('hoe',100,0,200))
        self.EinvMinusPinv = self.parse_axis(('emp',100,0,5))
        self.numMissingHits = self.parse_axis(('missing',10,0,10))
        self.passConvVeto = self.parse_axis(('passVeto',[0,1]))
        self.vxy_relDiff = self.parse_axis(('rel_diff',50,-2,2))
        self.isMatched = self.parse_axis(('matched',[0,1]))
        self.isPF = self.parse_axis(('isPF',[0,1]))
        self.numHits = self.parse_axis(('numHits',20,0,20))
        self.trkProb = self.parse_axis(('prob',100,0,1))
        self.IDScore = self.parse_axis(('id',100,-1,3))
        self.ele_passID = self.parse_axis(('passID',[0,1]))
        self.vtx_type = self.parse_axis(('vtype',['LL','LR','RR']))
        self.vtx_mass = self.parse_axis(('mass',100,0,30))
        self.vtx_sign = self.parse_axis(('sign',[-1,1]))
        self.vtx_pt = self.parse_axis(('pt',100,0,50))
        self.ele_ptRes = self.parse_axis(('ptres',100,-2,2))
        self.sigReco = self.parse_axis(('reco',[0,1]))
        self.vtxMatch = self.parse_axis(('match',[0,1]))
        self.dRCategories = self.parse_axis(('dRCat',['0to0p1','0p1to0p5','0p5toInf']))
        self.vxyCategories = self.parse_axis(('vxyCat',['0to1','1to5','5to10','10to15','15toInf']))
        self.ptCategories = self.parse_axis(('ptCat',['0to5','5to10','10to20','20toInf']))

    def make(self,name,*args,**hist_kwargs):
        if name in self.histograms.keys():
            print(f"Histogram {name} already exists! Skipping")
            return
        axes = [self.samp,self.cut]
        for ax in args:
            if type(ax) == tuple:
                axes.append(self.parse_axis(ax))
            else:
                axes.append(getattr(self,ax))
        self.histograms[name] = Hist(*axes,storage=hist.storage.Weight(),**hist_kwargs)
    
    def fill(self,name,**kwargs):
        self.histograms[name].fill(samp=self.samp,cut=self.cut,**kwargs)
    
    def parse_axis(self,a):
        name = a[0]
        if type(a[1]) == list:
            assert len(a) == 2
            if type(a[1][0]) == str:
                axis = StrCategory(a[1],name=name,label=name)
            else:
                axis = IntCategory(a[1],name=name,label=name)
        else:
            assert len(a) == 4
            axis = Regular(a[1],a[2],a[3],name=name,label=name)
        return axis

def make_histograms():
    h = myHisto()
    
    # quantities associated w/ gen objects
    h.make("gen_met",'met')
    h.make("gen_dR",'dR')
    h.make("gen_vxy1",'vxy1')
    h.make("gen_vxy10",'vxy10')
    h.make("gen_vxy100",'vxy100')
    h.make("gen_leadpT",'ele_pt')
    h.make("gen_vtx_METdPhi",'dphi')
    h.make("gen_jetMETdPhi",'dphi')
    h.make("gen_vtx_mass",'vtx_mass')
    h.make('gen_vtx_pt','vtx_pt')
    h.make('gen_vtx_eta','eta')
    h.make('gen_vtx_phi','phi')

    h.make("gen_met_unwgt",'met')
    h.make("gen_dR_unwgt",'dR')
    h.make("gen_vxy1_unwgt",'vxy1')
    h.make("gen_vxy10_unwgt",'vxy10')
    h.make("gen_vxy100_unwgt",'vxy100')
    h.make("gen_leadpT_unwgt",'ele_pt')
    h.make("gen_vtx_METdPhi_unwgt",'dphi')
    h.make("gen_jetMETdPhi_unwgt",'dphi')
    h.make("gen_vtx_mass_unwgt",'vtx_mass')
    h.make('gen_vtx_pt_unwgt','vtx_pt')
    h.make('gen_vtx_eta_unwgt','eta')
    h.make('gen_vtx_phi_unwgt','phi')

    h.make('gen_ele_pt','ele_pt')
    h.make('gen_ele_eta','eta')
    h.make('gen_ele_phi','phi')
    h.make('gen_ele_vxy1','vxy1')
    h.make('gen_ele_vxy10','vxy10')
    h.make('gen_ele_vxy100','vxy100')
    h.make("gen_ele_pt_vs_vxy1",'ele_pt','vxy1')
    h.make("gen_ele_pt_vs_vxy10",'ele_pt','vxy10')
    h.make("gen_ele_pt_vs_vxy100",'ele_pt','vxy100')
    h.make("gen_ele_pt_vs_dR",'ele_pt','dR')
    h.make("gen_ele_dR_vs_vxy1",'dR','vxy1')
    h.make("gen_ele_dR_vs_vxy10",'dR','vxy10')
    h.make("gen_ele_dR_vs_vxy100",'dR','vxy100')
    h.make("gen_ele_pt_vs_vxy1_dRBinned",'ele_pt','vxy1','dRCategories')
    h.make("gen_ele_pt_vs_vxy10_dRBinned",'ele_pt','vxy10','dRCategories')
    h.make("gen_ele_pt_vs_vxy100_dRBinned",'ele_pt','vxy100','dRCategories')
    h.make("gen_ele_pt_vs_dR_vxyBinned",'ele_pt','dR','vxyCategories')
    h.make("gen_ele_dR_vs_vxy1_ptBinned",'dR','vxy1','ptCategories')
    h.make("gen_ele_dR_vs_vxy10_ptBinned",'dR','vxy10','ptCategories')
    h.make("gen_ele_dR_vs_vxy100_ptBinned",'dR','vxy100','ptCategories')

    # reco --> vertexing efficiency
    h.make("signalReco_vs_vtxMatch",'sigReco','vtxMatch')
    h.make("signalReco_vs_vtxMatch_unwgt",'sigReco','vtxMatch')
    
    # matched reco electron, reco variables
    h.make("match_ele_pt",'match_type','ele_passID','ele_pt')
    h.make("match_ele_eta",'match_type','ele_passID','eta')
    h.make("match_ele_phi",'match_type','ele_passID','phi')
    h.make("match_ele_dxy",'match_type','ele_passID','dxy')
    h.make("match_ele_dxySignif",'match_type','ele_passID','dxy_signif')
    h.make("match_ele_trkChi2",'match_type','ele_passID','trk_chi2')
    h.make('match_ele_trkProb','match_type','ele_passID','trkProb')
    h.make("match_ele_trkRelIso",'match_type','ele_passID','iso')
    h.make("match_ele_calRelIso",'match_type','ele_passID','iso')
    h.make("match_ele_PFRelIso",'match_type','ele_passID','iso')
    h.make("match_ele_miniRelIso",'match_type','ele_passID','iso')
    h.make("match_ele_mindRJets",'match_type','ele_passID','dR')
    h.make("match_ele_isPF",'match_type','ele_passID','isPF')
    h.make("match_ele_numTrkHits",'match_type','ele_passID','numHits')
    h.make("match_ele_numPixHits",'match_type','ele_passID','numHits')
    h.make("match_ele_numStripHits",'match_type','ele_passID','numHits')
    h.make("match_ele_mindPhiJets",'match_type','ele_passID','dphi')
    h.make("match_ele_sigmaIetaIeta",'match_type','ele_passID','sieie')
    h.make("match_ele_absdEtaSeed",'match_type','ele_passID','detaseed')
    h.make("match_ele_absdPhiIn",'match_type','ele_passID','abs_dphi')
    h.make("match_ele_HOverE",'match_type','ele_passID','HoverE')
    h.make("match_ele_1E1p",'match_type','ele_passID','EinvMinusPinv')
    h.make("match_ele_expMissing",'match_type','ele_passID','numMissingHits')
    h.make("match_ele_passConvVeto",'match_type','ele_passID','passConvVeto')
    h.make("match_ele_IDscore",'match_type','ele_passID','IDScore')
    
    # matched reco electrons, corresponding gen object variables
    h.make("match_ele_gen_pt",'match_type','ele_passID','ele_pt')
    h.make('match_ele_gen_vxy1','match_type','ele_passID','vxy1')
    h.make('match_ele_gen_vxy10','match_type','ele_passID','vxy10')
    h.make('match_ele_gen_vxy100','match_type','ele_passID','vxy100')
    h.make('match_ele_gen_pt_vs_vxy1','match_type','ele_passID','ele_pt','vxy1')
    h.make('match_ele_gen_pt_vs_vxy10','match_type','ele_passID','ele_pt','vxy10')
    h.make('match_ele_gen_pt_vs_vxy100','match_type','ele_passID','ele_pt','vxy100')
    h.make("match_ele_gen_pt_vs_dR",'match_type','ele_passID','ele_pt','dR')
    h.make("match_ele_gen_dR_vs_vxy1",'match_type','ele_passID','dR','vxy1')
    h.make("match_ele_gen_dR_vs_vxy10",'match_type','ele_passID','dR','vxy10')
    h.make("match_ele_gen_dR_vs_vxy100",'match_type','ele_passID','dR','vxy100')
    h.make("match_ele_gen_eta",'match_type','ele_passID','eta')
    h.make('match_ele_gen_phi','match_type','ele_passID','phi')
    h.make('match_ele_gen_dR','match_type','ele_passID','dR')
    h.make('match_ele_ptRes','match_type','ele_passID','ele_ptRes')
    h.make("match_ele_gen_pt_vs_vxy1_dRBinned",'match_type','ele_passID','ele_pt','vxy1','dRCategories')
    h.make("match_ele_gen_pt_vs_vxy10_dRBinned",'match_type','ele_passID','ele_pt','vxy10','dRCategories')
    h.make("match_ele_gen_pt_vs_vxy100_dRBinned",'match_type','ele_passID','ele_pt','vxy100','dRCategories')
    h.make("match_ele_gen_pt_vs_dR_vxyBinned",'match_type','ele_passID','ele_pt','dR','vxyCategories')
    h.make("match_ele_gen_dR_vs_vxy1_ptBinned",'match_type','ele_passID','dR','vxy1','ptCategories')
    h.make("match_ele_gen_dR_vs_vxy10_ptBinned",'match_type','ele_passID','dR','vxy10','ptCategories')
    h.make("match_ele_gen_dR_vs_vxy100_ptBinned",'match_type','ele_passID','dR','vxy100','ptCategories')

    # fake reco electrons (not matched to a gen object)
    h.make("fake_ele_pt",'ele_type','ele_passID','ele_pt')
    h.make("fake_ele_eta",'ele_type','ele_passID','eta')
    h.make("fake_ele_phi",'ele_type','ele_passID','phi')
    h.make("fake_ele_dxy",'ele_type','ele_passID','dxy')
    h.make("fake_ele_dxySignif",'ele_type','ele_passID','dxy_signif')
    h.make("fake_ele_trkChi2",'ele_type','ele_passID','trk_chi2')
    h.make('fake_ele_trkProb','ele_type','ele_passID','trkProb')
    h.make("fake_ele_trkRelIso",'ele_type','ele_passID','iso')
    h.make("fake_ele_calRelIso",'ele_type','ele_passID','iso')
    h.make("fake_ele_PFRelIso",'ele_type','ele_passID','iso')
    h.make("fake_ele_miniRelIso",'ele_type','ele_passID','iso')
    h.make("fake_ele_mindRJets",'ele_type','ele_passID','dR')
    h.make("fake_ele_isPF",'ele_type','ele_passID','isPF')
    h.make("fake_ele_numTrkHits",'ele_type','ele_passID','numHits')
    h.make("fake_ele_numPixHits",'ele_type','ele_passID','numHits')
    h.make("fake_ele_numStripHits",'ele_type','ele_passID','numHits')
    h.make("fake_ele_mindPhiJets",'ele_type','ele_passID','dphi')
    h.make("fake_ele_sigmaIetaIeta",'ele_type','ele_passID','sieie')
    h.make("fake_ele_absdEtaSeed",'ele_type','ele_passID','detaseed')
    h.make("fake_ele_absdPhiIn",'ele_type','ele_passID','abs_dphi')
    h.make("fake_ele_HOverE",'ele_type','ele_passID','HoverE')
    h.make("fake_ele_1E1p",'ele_type','ele_passID','EinvMinusPinv')
    h.make("fake_ele_expMissing",'ele_type','ele_passID','numMissingHits')
    h.make("fake_ele_passConvVeto",'ele_type','ele_passID','passConvVeto')
    h.make("fake_ele_IDscore",'ele_type','ele_passID','IDScore')
    
    # matched reco vertex
    h.make("match_vtx_dR",'vtx_type','dR')
    h.make("match_vtx_mindxy",'vtx_type','dxy')
    h.make("match_vtx_vxy1",'vtx_type','vxy1')
    h.make("match_vtx_vxy10",'vtx_type','vxy10')
    h.make("match_vtx_vxy100",'vtx_type','vxy100')
    h.make("match_vtx_leadpT",'vtx_type','ele_pt')
    h.make("match_vtx_METdPhi",'vtx_type','dphi')
    h.make("match_vtx_mindRj",'vtx_type','dR')
    h.make("match_vtx_chi2",'vtx_type','vtx_chi2')
    h.make('match_vtx_mass','vtx_type','vtx_mass')
    h.make('match_vtx_mindPhiJ','vtx_type','dphi')
    h.make('match_vtx_sign','vtx_type','vtx_sign')
    h.make('match_vtx_pt','vtx_type','vtx_pt')
    h.make('match_vtx_eta','vtx_type','eta')
    h.make('match_vtx_phi','vtx_type','phi')
    h.make("match_vtx_type",'vtx_type')

    # matched reco vertex, corresponding gen features
    h.make("match_vtx_gen_dR",'vtx_type','dR')
    h.make("match_vtx_gen_vxy1",'vtx_type','vxy1')
    h.make("match_vtx_gen_vxy10",'vtx_type','vxy10')
    h.make("match_vtx_gen_vxy100",'vtx_type','vxy100')
    h.make("match_vtx_gen_METdPhi",'vtx_type','dphi')
    h.make("match_vtx_gen_mass",'vtx_type','vtx_mass')
    h.make('match_vtx_gen_pt','vtx_type','vtx_pt')
    h.make('match_vtx_gen_eta','vtx_type','eta')
    h.make('match_vtx_gen_phi','vtx_type','phi')
    h.make("match_vtx_reco_dR_vs_gen_dR",'vtx_type','dR',('gendR',250,0,5))
    h.make("match_vtx_reco_vxy1_vs_gen_vxy1",'vtx_type','vxy1',('genvxy',100,0,1))
    h.make("match_vtx_reco_vxy10_vs_gen_vxy10",'vtx_type','vxy10',('genvxy',100,0,10))
    h.make("match_vtx_reco_vxy100_vs_gen_vxy100",'vtx_type','vxy100',('genvxy',100,0,100))
    h.make("match_vtx_reco_METdPhi_vs_gen_METdPhi",'vtx_type','dphi',('gendphi',64,-3.2,3.2))
    h.make("match_vtx_reco_mass_vs_gen_mass",'vtx_type','vtx_mass',('gen_vtxmass',100,0,30))
    h.make('match_vtx_reco_pt_vs_gen_pt','vtx_type','vtx_pt',('gen_pt',100,0,50))
    h.make('match_vtx_reco_eta_vs_gen_eta','vtx_type','eta',('gen_eta',100,-2.5,2.5))
    h.make('match_vtx_reco_phi_vs_gen_phi','vtx_type','phi',('gen_phi',64,-3.2,.32))

    # fake reco vertices
    h.make("fake_vtx_dR",'vtx_type','dR')
    h.make("fake_vtx_mindxy",'vtx_type','dxy')
    h.make("fake_vtx_vxy1",'vtx_type','vxy1')
    h.make("fake_vtx_vxy10",'vtx_type','vxy10')
    h.make("fake_vtx_vxy100",'vtx_type','vxy100')
    h.make("fake_vtx_leadpT",'vtx_type','ele_pt')
    h.make("fake_vtx_METdPhi",'vtx_type','dphi')
    h.make("fake_vtx_mindRj",'vtx_type','dR')
    h.make("fake_vtx_chi2",'vtx_type','vtx_chi2')
    h.make('fake_vtx_mass','vtx_type','vtx_mass')
    h.make('fake_vtx_mindPhiJ','vtx_type','dphi')
    h.make('fake_vtx_sign','vtx_type','vtx_sign')
    h.make('fake_vtx_pt','vtx_type','vtx_pt')
    h.make('fake_vtx_eta','vtx_type','eta')
    h.make('fake_vtx_phi','vtx_type','phi')
    h.make("fake_vtx_type",'vtx_type')
    
    # misc other quantities
    h.make("PFMET",'met')
    h.make("PFMET_vs_genMET",'met',('genmet',100,50,300))


    return h

subroutines = []

def fillHistos(events,h,samp,cut,info,sum_wgt=1):
    h.samp = samp
    h.cut = cut
    wgt = events.eventWgt/sum_wgt
    
    if info["type"] == "signal":
        # defining stuff
        hasMatch_pf = (ak.count(events.Electron.pt,axis=1)>0) &\
                      (ak.count_nonzero(events.Electron.genMatched,axis=1)>0)

        hasMatch_lpt = (ak.count(events.LptElectron.pt,axis=1)>0) &\
                       (ak.count_nonzero(events.LptElectron.genMatched,axis=1)>0)

        match_pf = events[hasMatch_pf].Electron
        match_pf = match_pf[match_pf.genMatched]
        genObj_pf = ak.where(match_pf.matchType==-1,events[hasMatch_pf].GenEle,events[hasMatch_pf].GenPos)
        match_pf = ak.flatten(match_pf)
        genObj_pf = ak.flatten(genObj_pf)
        match_pf_passID = ak.values_astype(match_pf.passID,int)

        match_lpt = events[hasMatch_lpt].LptElectron
        match_lpt = match_lpt[match_lpt.genMatched]
        genObj_lpt = ak.where(match_lpt.matchType==-1,events[hasMatch_lpt].GenEle,events[hasMatch_lpt].GenPos)
        match_lpt = ak.flatten(match_lpt)
        genObj_lpt = ak.flatten(genObj_lpt)
        match_lpt_passID = ak.values_astype(match_lpt.passID,int)

        fake_pf = ak.flatten(events.Electron[~events.Electron.genMatched])
        fake_lpt = ak.flatten(events.LptElectron[~events.LptElectron.genMatched])

        fake_pf_passID = ak.values_astype(fake_pf.passID,int)
        fake_lpt_passID = ak.values_astype(fake_lpt.passID,int)

        match_vtx = ak.flatten(events.vtx[events.vtx.isMatched])
        match_vtx_genObj = events.genEE[ak.any(events.vtx.isMatched,axis=1)]
        fake_vtx = ak.flatten(events.vtx[~events.vtx.isMatched])

        hasMatchVtx = ak.values_astype(ak.any(events.vtx.isMatched,axis=1),int)
        signalReconstructed = ak.values_astype(events.signalReconstructed,int)

        ### FILLING HISTOGRAMS ###

        h.fill("gen_met",met=events.GenMET.pt,weight=wgt)
        h.fill("gen_dR",dR=events.genEE.dr,weight=wgt)
        h.fill("gen_vxy1",vxy=events.GenEle.vxy,weight=wgt)
        h.fill("gen_vxy10",vxy=events.GenEle.vxy,weight=wgt)
        h.fill("gen_vxy100",vxy=events.GenEle.vxy,weight=wgt)
        h.fill("gen_leadpT",pt=np.maximum(events.GenEle.pt,events.GenPos.pt),weight=wgt)
        h.fill("gen_vtx_METdPhi",phi=events.genEE.METdPhi,weight=wgt)
        h.fill("gen_jetMETdPhi",phi=events.GenJetMETdPhi,weight=wgt)
        h.fill("gen_vtx_mass",mass=events.genEE.mass,weight=wgt)
        h.fill('gen_vtx_pt',pt=events.genEE.pt,weight=wgt)
        h.fill('gen_vtx_eta',eta=events.genEE.eta,weight=wgt)
        h.fill('gen_vtx_phi',phi=events.genEE.phi,weight=wgt)
        
        
        h.fill("gen_met_unwgt",met=events.GenMET.pt,weight=1)
        h.fill("gen_dR_unwgt",dR=events.genEE.dr,weight=1)
        h.fill("gen_vxy1_unwgt",vxy=events.GenEle.vxy,weight=1)
        h.fill("gen_vxy10_unwgt",vxy=events.GenEle.vxy,weight=1)
        h.fill("gen_vxy100_unwgt",vxy=events.GenEle.vxy,weight=1)
        h.fill("gen_leadpT_unwgt",pt=np.maximum(events.GenEle.pt,events.GenPos.pt),weight=1)
        h.fill("gen_vtx_METdPhi_unwgt",phi=events.genEE.METdPhi,weight=1)
        h.fill("gen_jetMETdPhi_unwgt",phi=events.GenJetMETdPhi,weight=1)
        h.fill("gen_vtx_mass_unwgt",mass=events.genEE.mass,weight=1)
        h.fill('gen_vtx_pt_unwgt',pt=events.genEE.pt,weight=1)
        h.fill('gen_vtx_eta_unwgt',eta=events.genEE.eta,weight=1)
        h.fill('gen_vtx_phi_unwgt',phi=events.genEE.phi,weight=1)
        
        h.fill("gen_ele_pt",pt=events.GenEle.pt,weight=1)
        h.fill("gen_ele_pt",pt=events.GenPos.pt,weight=1)
        h.fill("gen_ele_vxy1",vxy=events.GenEle.vxy,weight=1)
        h.fill("gen_ele_vxy1",vxy=events.GenPos.vxy,weight=1)
        h.fill("gen_ele_vxy10",vxy=events.GenEle.vxy,weight=1)
        h.fill("gen_ele_vxy10",vxy=events.GenPos.vxy,weight=1)
        h.fill("gen_ele_vxy100",vxy=events.GenEle.vxy,weight=1)
        h.fill("gen_ele_vxy100",vxy=events.GenPos.vxy,weight=1)
        h.fill("gen_ele_pt_vs_vxy1",pt=events.GenEle.pt,vxy=events.GenEle.vxy,weight=1)
        h.fill("gen_ele_pt_vs_vxy1",pt=events.GenPos.pt,vxy=events.GenPos.vxy,weight=1)
        h.fill("gen_ele_pt_vs_vxy10",pt=events.GenEle.pt,vxy=events.GenEle.vxy,weight=1)
        h.fill("gen_ele_pt_vs_vxy10",pt=events.GenPos.pt,vxy=events.GenPos.vxy,weight=1)
        h.fill("gen_ele_pt_vs_vxy100",pt=events.GenEle.pt,vxy=events.GenEle.vxy,weight=1)
        h.fill("gen_ele_pt_vs_vxy100",pt=events.GenPos.pt,vxy=events.GenPos.vxy,weight=1)
        h.fill("gen_ele_pt_vs_dR",pt=events.GenEle.pt,dR=events.GenEle.dr,weight=1)
        h.fill("gen_ele_pt_vs_dR",pt=events.GenPos.pt,dR=events.GenPos.dr,weight=1)
        h.fill("gen_ele_dR_vs_vxy1",dR=events.GenEle.dr,vxy=events.GenEle.vxy,weight=1)
        h.fill("gen_ele_dR_vs_vxy1",dR=events.GenPos.dr,vxy=events.GenPos.vxy,weight=1)
        h.fill("gen_ele_dR_vs_vxy10",dR=events.GenEle.dr,vxy=events.GenEle.vxy,weight=1)
        h.fill("gen_ele_dR_vs_vxy10",dR=events.GenPos.dr,vxy=events.GenPos.vxy,weight=1)
        h.fill("gen_ele_dR_vs_vxy100",dR=events.GenEle.dr,vxy=events.GenEle.vxy,weight=1)
        h.fill("gen_ele_dR_vs_vxy100",dR=events.GenPos.dr,vxy=events.GenPos.vxy,weight=1)
        h.fill("gen_ele_pt_vs_vxy1_dRBinned",pt=events.GenEle.pt,vxy=events.GenEle.vxy,dRCat=events.GenEle.dRbin,weight=1)
        h.fill("gen_ele_pt_vs_vxy1_dRBinned",pt=events.GenPos.pt,vxy=events.GenPos.vxy,dRCat=events.GenPos.dRbin,weight=1)
        h.fill("gen_ele_pt_vs_vxy10_dRBinned",pt=events.GenEle.pt,vxy=events.GenEle.vxy,dRCat=events.GenEle.dRbin,weight=1)
        h.fill("gen_ele_pt_vs_vxy10_dRBinned",pt=events.GenPos.pt,vxy=events.GenPos.vxy,dRCat=events.GenPos.dRbin,weight=1)
        h.fill("gen_ele_pt_vs_vxy100_dRBinned",pt=events.GenEle.pt,vxy=events.GenEle.vxy,dRCat=events.GenEle.dRbin,weight=1)
        h.fill("gen_ele_pt_vs_vxy100_dRBinned",pt=events.GenPos.pt,vxy=events.GenPos.vxy,dRCat=events.GenPos.dRbin,weight=1)
        h.fill("gen_ele_pt_vs_dR_vxyBinned",pt=events.GenEle.pt,dR=events.GenEle.dr,vxyCat=events.GenEle.vxyBin,weight=1)
        h.fill("gen_ele_pt_vs_dR_vxyBinned",pt=events.GenPos.pt,dR=events.GenPos.dr,vxyCat=events.GenPos.vxyBin,weight=1)
        h.fill("gen_ele_dR_vs_vxy1_ptBinned",dR=events.GenEle.dr,vxy=events.GenEle.vxy,ptCat=events.GenEle.ptBin,weight=1)
        h.fill("gen_ele_dR_vs_vxy1_ptBinned",dR=events.GenPos.dr,vxy=events.GenPos.vxy,ptCat=events.GenPos.ptBin,weight=1)
        h.fill("gen_ele_dR_vs_vxy10_ptBinned",dR=events.GenEle.dr,vxy=events.GenEle.vxy,ptCat=events.GenEle.ptBin,weight=1)
        h.fill("gen_ele_dR_vs_vxy10_ptBinned",dR=events.GenPos.dr,vxy=events.GenPos.vxy,ptCat=events.GenPos.ptBin,weight=1)
        h.fill("gen_ele_dR_vs_vxy100_ptBinned",dR=events.GenEle.dr,vxy=events.GenEle.vxy,ptCat=events.GenEle.ptBin,weight=1)
        h.fill("gen_ele_dR_vs_vxy100_ptBinned",dR=events.GenPos.dr,vxy=events.GenPos.vxy,ptCat=events.GenPos.ptBin,weight=1)
        h.fill("gen_ele_eta",eta=events.GenEle.eta,weight=1)
        h.fill("gen_ele_eta",eta=events.GenPos.eta,weight=1)
        h.fill("gen_ele_phi",phi=events.GenEle.phi,weight=1)
        h.fill("gen_ele_phi",phi=events.GenPos.phi,weight=1)
        
        #
        h.fill('signalReco_vs_vtxMatch',reco=signalReconstructed,match=hasMatchVtx,weight=wgt)
        h.fill('signalReco_vs_vtxMatch_unwgt',reco=signalReconstructed,match=hasMatchVtx,weight=1)  
        
        #
        h.fill("match_ele_pt",match_type='R',passID=match_pf_passID,pt=match_pf.pt,weight=1)
        h.fill("match_ele_eta",match_type='R',passID=match_pf_passID,eta=match_pf.eta,weight=1)
        h.fill("match_ele_phi",match_type='R',passID=match_pf_passID,phi=match_pf.phi,weight=1)
        h.fill("match_ele_dxy",match_type='R',passID=match_pf_passID,dxy=match_pf.dxy,weight=1)
        h.fill("match_ele_dxySignif",match_type='R',passID=match_pf_passID,signif=match_pf.dxy/match_pf.dxyErr,weight=1)
        h.fill("match_ele_trkChi2",match_type='R',passID=match_pf_passID,chi2=match_pf.trkChi2,weight=1)
        h.fill("match_ele_trkProb",match_type='R',passID=match_pf_passID,prob=match_pf.trkProb)
        h.fill("match_ele_trkRelIso",match_type='R',passID=match_pf_passID,iso=match_pf.trkRelIso,weight=1)
        h.fill("match_ele_calRelIso",match_type='R',passID=match_pf_passID,iso=match_pf.calRelIso,weight=1)
        h.fill("match_ele_PFRelIso",match_type='R',passID=match_pf_passID,iso=match_pf.PFRelIso,weight=1)
        h.fill("match_ele_miniRelIso",match_type='R',passID=match_pf_passID,iso=match_pf.miniRelIso,weight=1)
        h.fill("match_ele_mindRJets",match_type='R',passID=match_pf_passID,dR=match_pf.mindRj,weight=1)
        h.fill("match_ele_mindPhiJets",match_type='R',passID=match_pf_passID,phi=match_pf.mindPhiJ,weight=1)
        h.fill('match_ele_isPF',match_type='R',passID=match_pf_passID,isPF=ak.values_astype(match_pf.isPF,int),weight=1)
        h.fill('match_ele_numTrkHits',match_type='R',passID=match_pf_passID,numHits=match_pf.numTrackerHits,weight=1)
        h.fill('match_ele_numPixHits',match_type='R',passID=match_pf_passID,numHits=match_pf.numPixHits,weight=1)
        h.fill('match_ele_numStripHits',match_type='R',passID=match_pf_passID,numHits=match_pf.numStripHits,weight=1)
        h.fill("match_ele_sigmaIetaIeta",match_type='R',passID=match_pf_passID,sieie=match_pf.full55sigmaIetaIeta,weight=1)
        h.fill("match_ele_absdEtaSeed",match_type='R',passID=match_pf_passID,detaSeed=match_pf.absdEtaSeed,weight=1)
        h.fill("match_ele_absdPhiIn",match_type='R',passID=match_pf_passID,phi=match_pf.absdPhiIn,weight=1)
        h.fill("match_ele_HOverE",match_type='R',passID=match_pf_passID,hoe=match_pf.HoverE,weight=1)
        h.fill("match_ele_1E1p",match_type='R',passID=match_pf_passID,emp=match_pf.abs1overEm1overP,weight=1)
        h.fill("match_ele_expMissing",match_type='R',passID=match_pf_passID,missing=match_pf.expMissingInnerHits,weight=1)
        h.fill("match_ele_passConvVeto",match_type='R',passID=match_pf_passID,passVeto=match_pf.conversionVeto,weight=1)
        h.fill("match_ele_IDscore",match_type='R',passID=match_pf_passID,id=match_pf.IDscore,weight=1)

        h.fill("match_ele_pt",match_type='L',passID=match_lpt_passID,pt=match_lpt.pt,weight=1)
        h.fill("match_ele_eta",match_type='L',passID=match_lpt_passID,eta=match_lpt.eta,weight=1)
        h.fill("match_ele_phi",match_type='L',passID=match_lpt_passID,phi=match_lpt.phi,weight=1)
        h.fill("match_ele_dxy",match_type='L',passID=match_lpt_passID,dxy=match_lpt.dxy,weight=1)
        h.fill("match_ele_dxySignif",match_type='L',passID=match_lpt_passID,signif=match_lpt.dxy/match_lpt.dxyErr,weight=1)
        h.fill("match_ele_trkChi2",match_type='L',passID=match_lpt_passID,chi2=match_lpt.trkChi2,weight=1)
        h.fill("match_ele_trkProb",match_type='L',passID=match_lpt_passID,prob=match_lpt.trkProb)
        h.fill("match_ele_trkRelIso",match_type='L',passID=match_lpt_passID,iso=match_lpt.trkRelIso,weight=1)
        h.fill("match_ele_calRelIso",match_type='L',passID=match_lpt_passID,iso=match_lpt.calRelIso,weight=1)
        h.fill("match_ele_PFRelIso",match_type='L',passID=match_lpt_passID,iso=match_lpt.PFRelIso,weight=1)
        h.fill("match_ele_miniRelIso",match_type='L',passID=match_lpt_passID,iso=match_lpt.miniRelIso,weight=1)
        h.fill("match_ele_mindRJets",match_type='L',passID=match_lpt_passID,dR=match_lpt.mindRj,weight=1)
        h.fill("match_ele_mindPhiJets",match_type='L',passID=match_lpt_passID,phi=match_lpt.mindPhiJ,weight=1)
        h.fill('match_ele_isPF',match_type='L',passID=match_lpt_passID,isPF=ak.values_astype(match_lpt.isPF,int),weight=1)
        h.fill('match_ele_numTrkHits',match_type='L',passID=match_lpt_passID,numHits=match_lpt.numTrackerHits,weight=1)
        h.fill('match_ele_numPixHits',match_type='L',passID=match_lpt_passID,numHits=match_lpt.numPixHits,weight=1)
        h.fill('match_ele_numStripHits',match_type='L',passID=match_lpt_passID,numHits=match_lpt.numStripHits,weight=1)
        h.fill("match_ele_sigmaIetaIeta",match_type='L',passID=match_lpt_passID,sieie=match_lpt.full55sigmaIetaIeta,weight=1)
        h.fill("match_ele_absdEtaSeed",match_type='L',passID=match_lpt_passID,detaSeed=match_lpt.absdEtaSeed,weight=1)
        h.fill("match_ele_absdPhiIn",match_type='L',passID=match_lpt_passID,phi=match_lpt.absdPhiIn,weight=1)
        h.fill("match_ele_HOverE",match_type='L',passID=match_lpt_passID,hoe=match_lpt.HoverE,weight=1)
        h.fill("match_ele_1E1p",match_type='L',passID=match_lpt_passID,emp=match_lpt.abs1overEm1overP,weight=1)
        h.fill("match_ele_expMissing",match_type='L',passID=match_lpt_passID,missing=match_lpt.expMissingInnerHits,weight=1)
        h.fill("match_ele_passConvVeto",match_type='L',passID=match_lpt_passID,passVeto=match_lpt.conversionVeto,weight=1)
        h.fill("match_ele_IDscore",match_type='L',passID=match_lpt_passID,id=match_lpt.IDscore,weight=1)
        
        #
        h.fill("match_ele_gen_pt",match_type='R',passID=match_pf_passID,pt=genObj_pf.pt,weight=1)
        h.fill("match_ele_gen_vxy1",match_type='R',passID=match_pf_passID,vxy=genObj_pf.vxy,weight=1)
        h.fill("match_ele_gen_vxy10",match_type='R',passID=match_pf_passID,vxy=genObj_pf.vxy,weight=1)
        h.fill("match_ele_gen_vxy100",match_type='R',passID=match_pf_passID,vxy=genObj_pf.vxy,weight=1)
        h.fill("match_ele_gen_pt_vs_vxy1",match_type='R',passID=match_pf_passID,pt=genObj_pf.pt,vxy=genObj_pf.vxy,weight=1)
        h.fill("match_ele_gen_pt_vs_vxy10",match_type='R',passID=match_pf_passID,pt=genObj_pf.pt,vxy=genObj_pf.vxy,weight=1)
        h.fill("match_ele_gen_pt_vs_vxy100",match_type='R',passID=match_pf_passID,pt=genObj_pf.pt,vxy=genObj_pf.vxy,weight=1)
        h.fill("match_ele_gen_pt_vs_dR",match_type='R',passID=match_pf_passID,pt=genObj_pf.pt,dR=genObj_pf.dr,weight=1)
        h.fill("match_ele_gen_dR_vs_vxy1",match_type='R',passID=match_pf_passID,dR=genObj_pf.dr,vxy=genObj_pf.vxy,weight=1)
        h.fill("match_ele_gen_dR_vs_vxy10",match_type='R',passID=match_pf_passID,dR=genObj_pf.dr,vxy=genObj_pf.vxy,weight=1)
        h.fill("match_ele_gen_dR_vs_vxy100",match_type='R',passID=match_pf_passID,dR=genObj_pf.dr,vxy=genObj_pf.vxy,weight=1)
        h.fill("match_ele_gen_eta",match_type='R',passID=match_pf_passID,eta=genObj_pf.eta,weight=1)
        h.fill("match_ele_gen_phi",match_type='R',passID=match_pf_passID,phi=genObj_pf.phi,weight=1)
        h.fill("match_ele_gen_dR",match_type='R',passID=match_pf_passID,dR=genObj_pf.dr,weight=1)
        h.fill("match_ele_ptRes",match_type='R',passID=match_pf_passID,ptres=(genObj_pf.pt-match_pf.pt)/genObj_pf.pt,weight=1)
        h.fill("match_ele_gen_pt_vs_vxy1_dRBinned",match_type='R',passID=match_pf_passID,pt=genObj_pf.pt,vxy=genObj_pf.vxy,dRCat=genObj_pf.dRbin,weight=1)
        h.fill("match_ele_gen_pt_vs_vxy10_dRBinned",match_type='R',passID=match_pf_passID,pt=genObj_pf.pt,vxy=genObj_pf.vxy,dRCat=genObj_pf.dRbin,weight=1)
        h.fill("match_ele_gen_pt_vs_vxy100_dRBinned",match_type='R',passID=match_pf_passID,pt=genObj_pf.pt,vxy=genObj_pf.vxy,dRCat=genObj_pf.dRbin,weight=1)
        h.fill("match_ele_gen_pt_vs_dR_vxyBinned",match_type='R',passID=match_pf_passID,pt=genObj_pf.pt,dR=genObj_pf.dr,vxyCat=genObj_pf.vxyBin,weight=1)
        h.fill("match_ele_gen_dR_vs_vxy1_ptBinned",match_type='R',passID=match_pf_passID,dR=genObj_pf.dr,vxy=genObj_pf.vxy,ptCat=genObj_pf.ptBin,weight=1)
        h.fill("match_ele_gen_dR_vs_vxy10_ptBinned",match_type='R',passID=match_pf_passID,dR=genObj_pf.dr,vxy=genObj_pf.vxy,ptCat=genObj_pf.ptBin,weight=1)
        h.fill("match_ele_gen_dR_vs_vxy100_ptBinned",match_type='R',passID=match_pf_passID,dR=genObj_pf.dr,vxy=genObj_pf.vxy,ptCat=genObj_pf.ptBin,weight=1)

        h.fill("match_ele_gen_pt",match_type='L',passID=match_lpt_passID,pt=genObj_lpt.pt,weight=1)
        h.fill("match_ele_gen_vxy1",match_type='L',passID=match_lpt_passID,vxy=genObj_lpt.vxy,weight=1)
        h.fill("match_ele_gen_vxy10",match_type='L',passID=match_lpt_passID,vxy=genObj_lpt.vxy,weight=1)
        h.fill("match_ele_gen_vxy100",match_type='L',passID=match_lpt_passID,vxy=genObj_lpt.vxy,weight=1)
        h.fill("match_ele_gen_pt_vs_vxy1",match_type='L',passID=match_lpt_passID,pt=genObj_lpt.pt,vxy=genObj_lpt.vxy,weight=1)
        h.fill("match_ele_gen_pt_vs_vxy10",match_type='L',passID=match_lpt_passID,pt=genObj_lpt.pt,vxy=genObj_lpt.vxy,weight=1)
        h.fill("match_ele_gen_pt_vs_vxy100",match_type='L',passID=match_lpt_passID,pt=genObj_lpt.pt,vxy=genObj_lpt.vxy,weight=1)
        h.fill("match_ele_gen_pt_vs_dR",match_type='L',passID=match_lpt_passID,pt=genObj_lpt.pt,dR=genObj_lpt.dr,weight=1)
        h.fill("match_ele_gen_dR_vs_vxy1",match_type='L',passID=match_lpt_passID,dR=genObj_lpt.dr,vxy=genObj_lpt.vxy,weight=1)
        h.fill("match_ele_gen_dR_vs_vxy10",match_type='L',passID=match_lpt_passID,dR=genObj_lpt.dr,vxy=genObj_lpt.vxy,weight=1)
        h.fill("match_ele_gen_dR_vs_vxy100",match_type='L',passID=match_lpt_passID,dR=genObj_lpt.dr,vxy=genObj_lpt.vxy,weight=1)
        h.fill("match_ele_gen_eta",match_type='L',passID=match_lpt_passID,eta=genObj_lpt.eta,weight=1)
        h.fill("match_ele_gen_phi",match_type='L',passID=match_lpt_passID,phi=genObj_lpt.phi,weight=1)
        h.fill("match_ele_gen_dR",match_type='L',passID=match_lpt_passID,dR=genObj_lpt.dr,weight=1)
        h.fill("match_ele_ptRes",match_type='L',passID=match_lpt_passID,ptres=(genObj_lpt.pt-match_lpt.pt)/genObj_lpt.pt,weight=1)
        h.fill("match_ele_gen_pt_vs_vxy1_dRBinned",match_type='L',passID=match_lpt_passID,pt=genObj_lpt.pt,vxy=genObj_lpt.vxy,dRCat=genObj_lpt.dRbin,weight=1)
        h.fill("match_ele_gen_pt_vs_vxy10_dRBinned",match_type='L',passID=match_lpt_passID,pt=genObj_lpt.pt,vxy=genObj_lpt.vxy,dRCat=genObj_lpt.dRbin,weight=1)
        h.fill("match_ele_gen_pt_vs_vxy100_dRBinned",match_type='L',passID=match_lpt_passID,pt=genObj_lpt.pt,vxy=genObj_lpt.vxy,dRCat=genObj_lpt.dRbin,weight=1)
        h.fill("match_ele_gen_pt_vs_dR_vxyBinned",match_type='L',passID=match_lpt_passID,pt=genObj_lpt.pt,dR=genObj_lpt.dr,vxyCat=genObj_lpt.vxyBin,weight=1)
        h.fill("match_ele_gen_dR_vs_vxy1_ptBinned",match_type='L',passID=match_lpt_passID,dR=genObj_lpt.dr,vxy=genObj_lpt.vxy,ptCat=genObj_lpt.ptBin,weight=1)
        h.fill("match_ele_gen_dR_vs_vxy10_ptBinned",match_type='L',passID=match_lpt_passID,dR=genObj_lpt.dr,vxy=genObj_lpt.vxy,ptCat=genObj_lpt.ptBin,weight=1)
        h.fill("match_ele_gen_dR_vs_vxy100_ptBinned",match_type='L',passID=match_lpt_passID,dR=genObj_lpt.dr,vxy=genObj_lpt.vxy,ptCat=genObj_lpt.ptBin,weight=1)

        #
        h.fill("fake_ele_pt",ele_type='R',passID=fake_pf_passID,pt=fake_pf.pt,weight=1)
        h.fill("fake_ele_eta",ele_type='R',passID=fake_pf_passID,eta=fake_pf.eta,weight=1)
        h.fill("fake_ele_phi",ele_type='R',passID=fake_pf_passID,phi=fake_pf.phi,weight=1)
        h.fill("fake_ele_dxy",ele_type='R',passID=fake_pf_passID,dxy=fake_pf.dxy,weight=1)
        h.fill("fake_ele_dxySignif",ele_type='R',passID=fake_pf_passID,signif=fake_pf.dxy/fake_pf.dxyErr,weight=1)
        h.fill("fake_ele_trkChi2",ele_type='R',passID=fake_pf_passID,chi2=fake_pf.trkChi2,weight=1)
        h.fill("fake_ele_trkProb",ele_type='R',passID=fake_pf_passID,prob=fake_pf.trkProb)
        h.fill("fake_ele_trkRelIso",ele_type='R',passID=fake_pf_passID,iso=fake_pf.trkRelIso,weight=1)
        h.fill("fake_ele_calRelIso",ele_type='R',passID=fake_pf_passID,iso=fake_pf.calRelIso,weight=1)
        h.fill("fake_ele_PFRelIso",ele_type='R',passID=fake_pf_passID,iso=fake_pf.PFRelIso,weight=1)
        h.fill("fake_ele_miniRelIso",ele_type='R',passID=fake_pf_passID,iso=fake_pf.miniRelIso,weight=1)
        h.fill("fake_ele_mindRJets",ele_type='R',passID=fake_pf_passID,dR=fake_pf.mindRj,weight=1)
        h.fill("fake_ele_mindPhiJets",ele_type='R',passID=fake_pf_passID,phi=fake_pf.mindPhiJ,weight=1)
        h.fill('fake_ele_isPF',ele_type='R',passID=fake_pf_passID,isPF=ak.values_astype(fake_pf.isPF,int),weight=1)
        h.fill('fake_ele_numTrkHits',ele_type='R',passID=fake_pf_passID,numHits=fake_pf.numTrackerHits,weight=1)
        h.fill('fake_ele_numPixHits',ele_type='R',passID=fake_pf_passID,numHits=fake_pf.numPixHits,weight=1)
        h.fill('fake_ele_numStripHits',ele_type='R',passID=fake_pf_passID,numHits=fake_pf.numStripHits,weight=1)
        h.fill("fake_ele_sigmaIetaIeta",ele_type='R',passID=fake_pf_passID,sieie=fake_pf.full55sigmaIetaIeta,weight=1)
        h.fill("fake_ele_absdEtaSeed",ele_type='R',passID=fake_pf_passID,detaSeed=fake_pf.absdEtaSeed,weight=1)
        h.fill("fake_ele_absdPhiIn",ele_type='R',passID=fake_pf_passID,phi=fake_pf.absdPhiIn,weight=1)
        h.fill("fake_ele_HOverE",ele_type='R',passID=fake_pf_passID,hoe=fake_pf.HoverE,weight=1)
        h.fill("fake_ele_1E1p",ele_type='R',passID=fake_pf_passID,emp=fake_pf.abs1overEm1overP,weight=1)
        h.fill("fake_ele_expMissing",ele_type='R',passID=fake_pf_passID,missing=fake_pf.expMissingInnerHits,weight=1)
        h.fill("fake_ele_passConvVeto",ele_type='R',passID=fake_pf_passID,passVeto=fake_pf.conversionVeto,weight=1)
        h.fill("fake_ele_IDscore",ele_type='R',passID=fake_pf_passID,id=fake_pf.IDscore,weight=1)

        h.fill("fake_ele_pt",ele_type='L',passID=fake_lpt_passID,pt=fake_lpt.pt,weight=1)
        h.fill("fake_ele_eta",ele_type='L',passID=fake_lpt_passID,eta=fake_lpt.eta,weight=1)
        h.fill("fake_ele_phi",ele_type='L',passID=fake_lpt_passID,phi=fake_lpt.phi,weight=1)
        h.fill("fake_ele_dxy",ele_type='L',passID=fake_lpt_passID,dxy=fake_lpt.dxy,weight=1)
        h.fill("fake_ele_dxySignif",ele_type='L',passID=fake_lpt_passID,signif=fake_lpt.dxy/fake_lpt.dxyErr,weight=1)
        h.fill("fake_ele_trkChi2",ele_type='L',passID=fake_lpt_passID,chi2=fake_lpt.trkChi2,weight=1)
        h.fill("fake_ele_trkProb",ele_type='L',passID=fake_lpt_passID,prob=fake_lpt.trkProb)
        h.fill("fake_ele_trkRelIso",ele_type='L',passID=fake_lpt_passID,iso=fake_lpt.trkRelIso,weight=1)
        h.fill("fake_ele_calRelIso",ele_type='L',passID=fake_lpt_passID,iso=fake_lpt.calRelIso,weight=1)
        h.fill("fake_ele_PFRelIso",ele_type='L',passID=fake_lpt_passID,iso=fake_lpt.PFRelIso,weight=1)
        h.fill("fake_ele_miniRelIso",ele_type='L',passID=fake_lpt_passID,iso=fake_lpt.miniRelIso,weight=1)
        h.fill("fake_ele_mindRJets",ele_type='L',passID=fake_lpt_passID,dR=fake_lpt.mindRj,weight=1)
        h.fill("fake_ele_mindPhiJets",ele_type='L',passID=fake_lpt_passID,phi=fake_lpt.mindPhiJ,weight=1)
        h.fill('fake_ele_isPF',ele_type='L',passID=fake_lpt_passID,isPF=ak.values_astype(fake_lpt.isPF,int),weight=1)
        h.fill('fake_ele_numTrkHits',ele_type='L',passID=fake_lpt_passID,numHits=fake_lpt.numTrackerHits,weight=1)
        h.fill('fake_ele_numPixHits',ele_type='L',passID=fake_lpt_passID,numHits=fake_lpt.numPixHits,weight=1)
        h.fill('fake_ele_numStripHits',ele_type='L',passID=fake_lpt_passID,numHits=fake_lpt.numStripHits,weight=1)
        h.fill("fake_ele_sigmaIetaIeta",ele_type='L',passID=fake_lpt_passID,sieie=fake_lpt.full55sigmaIetaIeta,weight=1)
        h.fill("fake_ele_absdEtaSeed",ele_type='L',passID=fake_lpt_passID,detaSeed=fake_lpt.absdEtaSeed,weight=1)
        h.fill("fake_ele_absdPhiIn",ele_type='L',passID=fake_lpt_passID,phi=fake_lpt.absdPhiIn,weight=1)
        h.fill("fake_ele_HOverE",ele_type='L',passID=fake_lpt_passID,hoe=fake_lpt.HoverE,weight=1)
        h.fill("fake_ele_1E1p",ele_type='L',passID=fake_lpt_passID,emp=fake_lpt.abs1overEm1overP,weight=1)
        h.fill("fake_ele_expMissing",ele_type='L',passID=fake_lpt_passID,missing=fake_lpt.expMissingInnerHits,weight=1)
        h.fill("fake_ele_passConvVeto",ele_type='L',passID=fake_lpt_passID,passVeto=fake_lpt.conversionVeto,weight=1)
        h.fill("fake_ele_IDscore",ele_type='L',passID=fake_lpt_passID,id=fake_lpt.IDscore,weight=1)

        #
        h.fill("match_vtx_dR",vtype=match_vtx.typ,dR=match_vtx.dR,weight=1)
        h.fill("match_vtx_mindxy",vtype=match_vtx.typ,dxy=match_vtx.minDxy,weight=1)
        h.fill("match_vtx_vxy1",vtype=match_vtx.typ,vxy=match_vtx.vxy,weight=1)
        h.fill("match_vtx_vxy10",vtype=match_vtx.typ,vxy=match_vtx.vxy,weight=1)
        h.fill("match_vtx_vxy100",vtype=match_vtx.typ,vxy=match_vtx.vxy,weight=1)
        h.fill("match_vtx_leadpT",vtype=match_vtx.typ,pt=np.maximum(match_vtx.e1.pt,match_vtx.e2.pt),weight=1)
        h.fill("match_vtx_METdPhi",vtype=match_vtx.typ,phi=match_vtx.METdPhi,weight=1)
        h.fill('match_vtx_mindRj',vtype=match_vtx.typ,dR=match_vtx.mindRj,weight=1)
        h.fill('match_vtx_chi2',vtype=match_vtx.typ,chi2=match_vtx.reduced_chi2,weight=1)
        h.fill('match_vtx_mass',vtype=match_vtx.typ,mass=match_vtx.m,weight=1)
        h.fill('match_vtx_mindPhiJ',vtype=match_vtx.typ,phi=match_vtx.mindPhiJ,weight=1)
        h.fill('match_vtx_sign',vtype=match_vtx.typ,sign=match_vtx.sign,weight=1)
        h.fill('match_vtx_pt',vtype=match_vtx.typ,pt=match_vtx.pt,weight=1)
        h.fill('match_vtx_eta',vtype=match_vtx.typ,eta=match_vtx.eta,weight=1)
        h.fill('match_vtx_phi',vtype=match_vtx.typ,phi=match_vtx.phi,weight=1)
        h.fill('match_vtx_type',vtype=match_vtx.typ,weight=1)

        #
        h.fill("match_vtx_gen_dR",vtype=match_vtx.typ,dR=match_vtx_genObj.dr,weight=1)
        h.fill("match_vtx_gen_vxy1",vtype=match_vtx.typ,vxy=match_vtx_genObj.vxy,weight=1)
        h.fill("match_vtx_gen_vxy10",vtype=match_vtx.typ,vxy=match_vtx_genObj.vxy,weight=1)
        h.fill("match_vtx_gen_vxy100",vtype=match_vtx.typ,vxy=match_vtx_genObj.vxy,weight=1)
        h.fill("match_vtx_gen_METdPhi",vtype=match_vtx.typ,phi=match_vtx_genObj.METdPhi,weight=1)
        h.fill("match_vtx_gen_mass",vtype=match_vtx.typ,mass=match_vtx_genObj.mass,weight=1)
        h.fill("match_vtx_gen_pt",vtype=match_vtx.typ,pt=match_vtx_genObj.pt,weight=1)
        h.fill("match_vtx_gen_eta",vtype=match_vtx.typ,eta=match_vtx_genObj.eta,weight=1)
        h.fill("match_vtx_gen_phi",vtype=match_vtx.typ,phi=match_vtx_genObj.phi,weight=1)
        h.fill("match_vtx_reco_dR_vs_gen_dR",vtype=match_vtx.typ,dR=match_vtx.dR,gendR=match_vtx_genObj.dr,weight=1)
        h.fill("match_vtx_reco_vxy1_vs_gen_vxy1",vtype=match_vtx.typ,vxy=match_vtx.vxy,genvxy=match_vtx_genObj.vxy,weight=1)
        h.fill("match_vtx_reco_vxy10_vs_gen_vxy10",vtype=match_vtx.typ,vxy=match_vtx.vxy,genvxy=match_vtx_genObj.vxy,weight=1)
        h.fill("match_vtx_reco_vxy100_vs_gen_vxy100",vtype=match_vtx.typ,vxy=match_vtx.vxy,genvxy=match_vtx_genObj.vxy,weight=1)
        h.fill("match_vtx_reco_METdPhi_vs_gen_METdPhi",vtype=match_vtx.typ,phi=match_vtx.METdPhi,gendphi=match_vtx_genObj.METdPhi,weight=1)
        h.fill("match_vtx_reco_mass_vs_gen_mass",vtype=match_vtx.typ,mass=match_vtx.m,gen_vtxmass=match_vtx_genObj.mass,weight=1)
        h.fill("match_vtx_reco_pt_vs_gen_pt",vtype=match_vtx.typ,pt=match_vtx.pt,gen_pt=match_vtx_genObj.pt,weight=1)
        h.fill("match_vtx_reco_eta_vs_gen_eta",vtype=match_vtx.typ,eta=match_vtx.eta,gen_eta=match_vtx_genObj.eta,weight=1)
        h.fill("match_vtx_reco_phi_vs_gen_phi",vtype=match_vtx.typ,phi=match_vtx.phi,gen_phi=match_vtx_genObj.eta,weight=1)
        
        #
        h.fill("fake_vtx_dR",vtype=fake_vtx.typ,dR=fake_vtx.dR,weight=1)
        h.fill("fake_vtx_mindxy",vtype=fake_vtx.typ,dxy=fake_vtx.minDxy,weight=1)
        h.fill("fake_vtx_vxy1",vtype=fake_vtx.typ,vxy=fake_vtx.vxy,weight=1)
        h.fill("fake_vtx_vxy10",vtype=fake_vtx.typ,vxy=fake_vtx.vxy,weight=1)
        h.fill("fake_vtx_vxy100",vtype=fake_vtx.typ,vxy=fake_vtx.vxy,weight=1)
        h.fill("fake_vtx_leadpT",vtype=fake_vtx.typ,pt=np.maximum(fake_vtx.e1.pt,fake_vtx.e2.pt),weight=1)
        h.fill("fake_vtx_METdPhi",vtype=fake_vtx.typ,phi=fake_vtx.METdPhi,weight=1)
        h.fill('fake_vtx_mindRj',vtype=fake_vtx.typ,dR=fake_vtx.mindRj,weight=1)
        h.fill('fake_vtx_chi2',vtype=fake_vtx.typ,chi2=fake_vtx.reduced_chi2,weight=1)
        h.fill('fake_vtx_mass',vtype=fake_vtx.typ,mass=fake_vtx.m,weight=1)
        h.fill('fake_vtx_mindPhiJ',vtype=fake_vtx.typ,phi=fake_vtx.mindPhiJ,weight=1)
        h.fill('fake_vtx_sign',vtype=fake_vtx.typ,sign=fake_vtx.sign,weight=1)
        h.fill('fake_vtx_pt',vtype=fake_vtx.typ,pt=fake_vtx.pt,weight=1)
        h.fill('fake_vtx_eta',vtype=fake_vtx.typ,eta=fake_vtx.eta,weight=1)
        h.fill('fake_vtx_phi',vtype=fake_vtx.typ,phi=fake_vtx.phi,weight=1)
        h.fill('fake_vtx_type',vtype=fake_vtx.typ,weight=1)

        #
        h.fill("PFMET",met=events.PFMET.pt,weight=wgt)
        h.fill("PFMET_vs_genMET",met=events.PFMET.pt,genmet=events.GenMET.pt,weight=1)